server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  absolute_redirect off;

  location = __APP_BASE_PATH__ {
    return 301 __APP_BASE_PATH__/;
  }

  location __APP_BASE_PATH__/ {
    try_files $uri $uri/ __APP_BASE_PATH__/index.html;
  }
}
