server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /kopic {
    return 301 /kopic/;
  }

  location /kopic/ {
    try_files $uri $uri/ /kopic/index.html;
  }
}
